apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NAME_WILL_BE_FILLED_IN
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: NS_WILL_BE_FILLED_IN
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: REPO_WILL_BE_FILLED_IN
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
